---
kind: Simulation
metadata:
  labels:
    generator: ast convert
    input_file: cmd/ast/testdata/dsl/stacks.ast.json
spec:
  arch: linux-x86
  channels:
    - name: physical
      networks: []
  stacks:
    - models:
        - arch: linux-amd64
          channels:
            - alias: scalar
              name: physical
          model: dse.fmi.mcl
          name: one
          uses: ""
          workflows: []
      name: default
    - arch: win-x86
      models:
        - channels:
            - alias: scalar
              name: physical
          model: dse.fmi.mcl
          name: two
          uses: ""
          workflows: []
      name: stack-stacked
      stacked: true
    - models:
        - arch: linux-i386
          channels:
            - alias: scalar
              name: physical
          model: dse.fmi.mcl
          name: three
          uses: ""
          workflows: []
      name: model-arch
  uses:
    - name: dse.fmi
      url: https://github.com/boschglobal/dse.fmi
      version: v1.1.8
  vars: []
---
kind: Simulation
metadata:
  labels:
    generator: ast convert
    input_file: cmd/ast/testdata/dsl/model.ast.json
spec:
  arch: linux-amd64
  channels:
    - name: physical
      networks: []
    - name: network
      networks:
        - mime_type: application/x-automotive-bus;interface=stream;type=frame;bus=can;schema=fbs;bus_id=1
          name: CAN
  stacks:
    - models:
        - channels:
            - alias: scalar_vector
              name: physical
            - alias: network_vector
              name: network
          model: dse.fmi.mcl
          name: FMU
          uses: ""
          workflows:
            - name: generate
              vars:
                - name: model_uses
                  reference: uses
                  value: fmu
                - name: model_key
                  value: model_val
      name: default
  uses:
    - name: dse.fmi
      url: https://github.com/boschglobal/dse.fmi
      version: v1.1.8
    - name: fmu
      url: https://artifactory.bosch/examples/fmu.zip
      version: v1.0.0
  vars:
    - name: sim_key
      value: sim_value
